name: target
shell: target
requires: [renode_config]
echo: true
timeout: 50
fail-fast: true
commands:
  - expect: "buildroot login:"
    timeout: 300
    check-exit-code: False
  - root
  - dmesg -n 1
  - date -s "${{NOW}}"
